Feature/asynchronous operations learning
IT-Sadok/Vladyslav pull request #5
Opened 2024-07-09 11:22 UTC by VladMakarenko99

2024-07-09 14:08 UTC, sawabond requested changes
Good job, very good use cases. For training purposes I proposed more use cases

2024-07-09 14:08 UTC, sawabond commented on HealthcareApp/src/Healthcare.Domain/Constants/DefaultWorkingHours.cs
> +        startOfWeek = startOfWeek.Date; // Just to make sure we are working with dates only
There is `DateOnly` and `TimeOnly` to work with date or time only

2024-07-09 14:08 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/AsyncExamples/AsyncExamples.cs
> +    }
Add example with configure await false/true, and add comments and console logs on which Thread/SynchronizationContext we are returning after awaiting. Because this sample does not show the meaning of ConfigureAwait

2024-07-09 14:08 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/AsyncExamples/AsyncExamples.cs
> +        Console.WriteLine("Long-running task completed.");
Write comments what's the difference between: `new Task(() => ...), Task.Run, and Task.Factory.StartNew`.
Please also write why and in what cases we should use LongRunning task options

2024-07-09 14:08 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/Operations/CpuBoundOperations.cs
> +        });
Refactor to use Parallel with parallelism degree.
As a sample also add PLINQ example

2024-07-09 14:08 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/SynchronizationPrimitives/LockExample.cs
> +}
Add the same sample with `ReaderWriterLockSlim`

2024-07-09 14:08 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/SynchronizationPrimitives/SpinWaitExample.cs
> +namespace LearnMultithreading.SynchronizationPrimitives;
Not related to this file but:
- still need to add `ValueTask<T>` usage
- Concurrent, Immutable collections

2024-07-23 10:20 UTC, VladMakarenko99 commented on HealthcareApp/src/Healthcare.Domain/Constants/DefaultWorkingHours.cs
> +        startOfWeek = startOfWeek.Date; // Just to make sure we are working with dates only
Yes, however, I cannot use it here because domain enity has property of type `DateTime`

2024-07-23 11:09 UTC, VladMakarenko99 commented on HealthcareApp/src/LearnMultithreading/Operations/CpuBoundOperations.cs
> +        });
Rewrote the method to be a parallel sequence. But also I actually have the one example of PLINQ in Program.cs in line 119, have you seen it?

2024-07-23 20:47 UTC, sawabond approved these changes
Accepted

2024-07-23 20:47 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/AsyncExamples/ValueTaskExample.cs
> +    public static async ValueTask<TimeSlotsDictionary> FetchData()
I cannot see any benefits of value task here

2024-07-23 20:47 UTC, sawabond commented on HealthcareApp/src/LearnMultithreading/SynchronizationPrimitives/ReaderWriterLockSlimExample.cs
> +        }
I think in the example you should show that you are readinmg Much More Frequently than write

2024-07-31 10:38 UTC, merged